name: Actions Runner Controller Demo
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted,example-runner-deployment]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running on a self-hosted runner"
